<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LiftoffPath>/home/dev-user/.steam/debian-installation/steamapps/common/Liftoff</LiftoffPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="libs/**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/PhotonRealtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/Photon3Unity3D.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>$(LiftoffPath)/Liftoff_Data/Managed/com.rlabrecque.steamworks.net.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(LiftoffPath)/BepInEx/core/BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(LiftoffPath)/BepInEx/core/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(OutputPath)/LiftoffAutoLobby.dll" DestinationFolder="$(LiftoffPath)/BepInEx/plugins/" />
  </Target>

</Project>
